services:
  db_agricultura:
    container_name: db_agricultura
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: db_agricultura
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  app:
    container_name: app_agriculture
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db_agricultura
    environment:
      - HOST_DB=db_agricultura
      - USERNAME_DB=postgres
      - PASSWORD_DB=1234
      - DATABASE=db_agricultura
      - VIA_CEP_API_URL=https://viacep.com.br/ws/
      - LOGGIN=true
      - LOG_RULES='level=error'
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  pgdata: {}
